FROM python:3.12-slim

WORKDIR /app

COPY shortener-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shortener-service/ .
COPY proto/ proto/

RUN chmod +x start.sh

EXPOSE 8000

CMD ["./start.sh"]
