apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-analytics-pvc
  namespace: urlshort
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-analytics
  namespace: urlshort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-analytics
  template:
    metadata:
      labels:
        app: postgres-analytics
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: analytics
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-analytics-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-analytics-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "analytics_user", "-d", "analytics"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-analytics-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-analytics
  namespace: urlshort
spec:
  selector:
    app: postgres-analytics
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-analytics-secret
  namespace: urlshort
type: Opaque
stringData:
  username: analytics_user
  password: analytics_pass_2024
